### PR TITLE
Add CI to r2_loo()

### PR DESCRIPTION
**Pull request by bwiernik**
Method pulled from *rstanarm*

### CODE REVIEW

**Comment by strengejacke** [comment]
`sweep()` is one of the remaining R mysteries to me ;-)
Should this PR merged before we submit a new version to CRAN? I'm preparing CRAN submission of _performance_ for the next days.

**Comment by bwiernik** [comment]
The computational code is lifted from rstanarm. Here, sweep is used to multiple each column of `wts` by either the observed response values or the posterior draws. This is used to compute row-wise variances.

I think we can merge this before CRAN.

**Comment by bwiernik** [comment]
Realized that *rstantools* has the same function implemented, so I changed our function to just wrap that in the same way as with `r2_bayes()`.

**Comment by bwiernik** [comment]
Okay @strengejacke This now passes all the tests and checks, so I think we can merge before CRAN release

**Pull request merged**
