### PR TITLE
Draf check_model vignette

### LINKED ISSUE #395: Documentation for `check_model()`
@bwiernik @IndrajeetPatil @DominiqueMakowski @mattansb I think a very common question is how to interprete these plots. We already have some more details in the docs, but probably we should provide some guidelines about the meaning of these plots in the docs:

https://easystats.github.io/performance/reference/check_model.html

_Originally posted by @strengejacke in https://github.com/easystats/see/issues/211#issuecomment-1056397023_

### PR DESCRIPTION
**Pull request by strengejacke**
Fixes #395

### CODE REVIEW

**Comment by bwiernik** [comment]
Did you see the vignette branch?

**Comment by strengejacke** [comment]
No... 🙈

**Comment by strengejacke** [comment]
@bwiernik how do we want to proceed?

**Comment by strengejacke** [comment]
Brenton, I'll merge this for now, but we can either replace by, add or merge with your draft you're working on to avoid redundancies.

**Pull request merged**
