### PR TITLE
switch to poorman; avoid em-dash

### PR DESCRIPTION
**Pull request by IndrajeetPatil**
- https://github.com/easystats/easystats/issues/168

- https://github.com/easystats/easystats/issues/188

- styling

### CODE REVIEW

**Comment by bwiernik** [comment]
(That's an en dash – not an em dash —)

The way to safely do en and em dashes in markdown/Rd is to use 2 or 3 hyphens

`--` = –
`---` = —

**Comment by IndrajeetPatil** [comment]
Oh?

Regardless, I have only replaced the character (en- or em-dash) that was producing this in RStudio help pane with a regular dash:

image

**Comment by bwiernik** [comment]
Making my typsetter eyes bleed by pretending a hyphen-minus is an en dash 😭

**Comment by IndrajeetPatil** [comment]
giphy

**Pull request merged**
