### PR TITLE
add R2 CI

### PR DESCRIPTION
**Pull request by strengejacke**

### CODE REVIEW

**Comment by strengejacke** [comment]
closes #256

**Comment by strengejacke** [comment]
Looks good, @bwiernik @DominiqueMakowski ?

``` r
library(performance)
m <- lm(formula = mpg ~ wt + qsec + am, data = mtcars)
performance:::confint_r2(m)
#>          R2    CI_low  CI_high
#> 1 0.8496636 0.6820641 0.916607
```

<sup>Created on 2021-04-05 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by strengejacke** [comment]
Any suggestions how to implement this? Should we add an additional argument (like `ci`, that defaults to `NULL` / `NA`, and if given, includes the CI?)

**Comment by strengejacke** [comment]
@bwiernik Any references for this approach that we could add to the docs?

**Comment by bwiernik** [comment]
Based on Shieh, G. (2006). Exact interval estimation, power calculation, and sample size determination in normal correlation analysis. Psychometrika, 71(3), 529. https://doi.org/10.1007/s11336-04-1221-6

**Comment by strengejacke** [comment]
for some models, it fails. So we should wrap this function into `tryCatch()`:

``` r
library(performance)
m <- lm(formula = mpg ~ wt + qsec + am, data = mtcars)
performance:::.confint_r2(m)
#> $R2
#>        R2    CI_low   CI_high 
#> 0.8496636 0.6820641 0.9166070 
#> 
#> $R2_adjusted
#> adjusted R2      CI_low     CI_high 
#>   0.8335561   0.6516598   0.9072481


model <- glm(vs ~ wt + mpg, data = mtcars, family = "binomial")
performance:::.confint_r2(model)
#> $R2_Tjur
#> Tjur's R2    CI_low   CI_high 
#> 0.4776926 0.1728083 0.6836999


# example from ?glm
counts <- c(18,17,15,20,10,20,25,13,12)
outcome <- gl(3,1,9)
treatment <- gl(3,3)
d <- data.frame(treatment, outcome, counts)
glm.D93 <- glm(counts ~ outcome + treatment, family = poisson(), data = d)
performance:::.confint_r2(glm.D93)
#> Error in stats::uniroot(.pRsq, c(1e-05, 0.99999), R2_obs = as.vector(rsq), : f() values at end points not of opposite sign
```

<sup>Created on 2021-04-05 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by bwiernik** [comment]
I've only thought about this in the context of linear models, so I'm not sure about performance for GLMs, especially not for various flavors of R2.

**Comment by bwiernik** [comment]
Perhaps we should add a `method` argument and include bootstrap as an option. We could limit methods to bootstrap unless a solid analytic method is available.

**Comment by DominiqueMakowski** [comment]
> Should we add an additional argument (like ci, that defaults to NULL / NA, and if given, includes the CI?)

I think that models where an analytical method is straightforward we can return it by default. Better to have more information by default (especially popular concepts like CI) than not

**Comment by bwiernik** [comment]
@strengejacke Just checking on the status of this? What are the issues still to be resolved? I think it would be useful to merge in the option for CIs for R2/sigma on `lm` and Gaussian `glm` models. We can check on other forms of GLMs and multilevel models in the future. 

For Bayesian models, this is already all handled by the posterior.

**Comment by mattansb** [comment]
Just to note that in `effectsize`....

```R
m <- lm(mpg ~ ., mtcars)

summary(m)
#> 
#> Call:
#> lm(formula = mpg ~ ., data = mtcars)
#> 
#> Residuals:
#>     Min      1Q  Median      3Q     Max 
#> -3.4506 -1.6044 -0.1196  1.2193  4.6271 
#> 
#> Coefficients:
#>  Estimate Std. Error t value Pr(>|t|)  
#> (Intercept) 12.30337   18.71788   0.657   0.5181  
#> cyl         -0.11144    1.04502  -0.107   0.9161  
#> disp         0.01334    0.01786   0.747   0.4635  
#> hp          -0.02148    0.02177  -0.987   0.3350  
#> drat         0.78711    1.63537   0.481   0.6353  
#> wt          -3.71530    1.89441  -1.961   0.0633 .
#> qsec         0.82104    0.73084   1.123   0.2739  
#> vs           0.31776    2.10451   0.151   0.8814  
#> am           2.52023    2.05665   1.225   0.2340  
#> gear         0.65541    1.49326   0.439   0.6652  
#> carb        -0.19942    0.82875  -0.241   0.8122  
#> ---
#> Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1
#> 
#> Residual standard error: 2.65 on 21 degrees of freedom
#> Multiple R-squared:  0.869,	Adjusted R-squared:  0.8066 
#> F-statistic: 13.93 on 10 and 21 DF,  p-value: 3.793e-07 # <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< Here

performance::r2(m)
#> # R2 for Linear Regression
#>        R2: 0.869
#>   adj. R2: 0.807

# Same estimates + CIs
effectsize::F_to_eta2(13.93, 10, 21) |> print(digits = 3)
#> Eta2 (partial) |         95% CI
#> -------------------------------
#> 0.869          | [0.743, 1.000]
#> 
#> - One-sided CIs: upper bound fixed at (1).
effectsize::F_to_eta2_adj(13.93, 10, 21) |> print(digits = 3)
#> Epsilon2 (partial) |         95% CI
#> -----------------------------------
#> 0.807              | [0.609, 1.000]
#> 
#> - One-sided CIs: upper bound fixed at (1).
```

**Comment by strengejacke** [comment]
Running checks now

**Comment by bwiernik** [comment]
It doesn't look like the CI is actually added to the output?

**Pull request merged**
