### PR TITLE
`check_outliers` thresholds and distance scores improvements

### PR DESCRIPTION
**Pull request by rempsyc**
Closes \#467

------------------------------------------------------------------------

### The Percentile Score…

In my early testing with a single column, I found that it made sense to take the percentile for the distance score, like agreed, to detect outliers with `check_outliers()`. However, things get more complicated when having to compute the aggregate score for a summary of all columns of a dataframe. With a regular distance score, like zscore, the bigger the deviation, the bigger the score, so in this case we can safely use the max.

However, for percentile, you can’t just take the max, because then it will only show those above the upper threshold, but not those under the lower threshold. Therefore, it might make more sense to actually calculate a new, absolute distance score.

My first attempt was using the absolute deviation from the 50th percentile/median. This seemed to make sense, but it was problematic because sometimes it didn’t match with the decision criteria (higher values not flagged as outliers, and vice-versa). This is because the 50th percentile is not always equivalent to the median of the upper and lower bounds as defined by the IQR method.

### New Strategy

Therefore, for the IQR, we now have: the absolute deviation from the median of the upper and lower IQR thresholds. Then, we divide this value by the IQR threshold, to “standardize” it and facilitate interpretation.

``` r
lower <- stats::quantile(v, 0.25, na.rm = TRUE) - (iqr * threshold)
upper <- stats::quantile(v, 0.75, na.rm = TRUE) + (iqr * threshold)
m.int <- stats::median(c(lower, upper), na.rm = TRUE)
d2 <- abs(v - m.int)
Distance_IQR[names(as.data.frame(x))[col]] <- d2/(iqr * threshold)
```

For the CI methods, we now have: the absolute deviation from the median of the upper and lower CI thresholds. Then, we divide this value by the difference between the upper and lower CI bounds divided by two, to “standardize” it and facilitate interpretation.

``` r
m.int <- stats::median(c(ci$CI_low, ci$CI_high), na.rm = TRUE)
d2 <- abs(v - m.int)
ci.range <- (ci$CI_high - ci$CI_low)/2
```

I think we would need a place to describe those new distance scores. I put them for now in the description of the methods (`#' @section Univariate methods`), but it could also go in the “value” section.

@bwiernik, do these new distance scores make any sense to you? And do you know of any references for them? If so perhaps we should add them.

### Reprex:

``` r
# Before
library(performance)
# Single score
z <- check_outliers(mtcars$mpg, method = c("iqr", "ci"), threshold = 0.7)
z.att <- attributes(z)
z.att$data
#>    Row Distance_IQR Outlier_IQR Distance_ci Outlier_ci Outlier
#> 1    1            0           0           0          0     0.0
#> 2    2            0           0           0          0     0.0
#> 3    3            0           0           0          0     0.0
#> 4    4            0           0           0          0     0.0
#> 5    5            0           0           0          0     0.0
#> 6    6            0           0           0          0     0.0
#> 7    7            0           0           1          1     0.5
#> 8    8            0           0           0          0     0.0
#> 9    9            0           0           0          0     0.0
#> 10  10            0           0           0          0     0.0
#> 11  11            0           0           0          0     0.0
#> 12  12            0           0           0          0     0.0
#> 13  13            0           0           0          0     0.0
#> 14  14            0           0           0          0     0.0
#> 15  15            0           0           1          1     0.5
#> 16  16            0           0           1          1     0.5
#> 17  17            0           0           1          1     0.5
#> 18  18            1           1           1          1     1.0
#> 19  19            1           1           1          1     1.0
#> 20  20            1           1           1          1     1.0
#> 21  21            0           0           0          0     0.0
#> 22  22            0           0           0          0     0.0
#> 23  23            0           0           0          0     0.0
#> 24  24            0           0           1          1     0.5
#> 25  25            0           0           0          0     0.0
#> 26  26            0           0           1          1     0.5
#> 27  27            0           0           0          0     0.0
#> 28  28            1           1           1          1     1.0
#> 29  29            0           0           0          0     0.0
#> 30  30            0           0           0          0     0.0
#> 31  31            0           0           0          0     0.0
#> 32  32            0           0           0          0     0.0

# Dataframe
z <- check_outliers(mtcars, method = c("iqr", "ci"), threshold = 0.7)
z.att <- attributes(z)
z.att$data
#>    Row Distance_IQR Outlier_IQR Distance_ci Outlier_ci Outlier
#> 1    1   0.00000000           0  0.00000000          0     0.0
#> 2    2   0.00000000           0  0.00000000          0     0.0
#> 3    3   0.00000000           0  0.00000000          0     0.0
#> 4    4   0.00000000           0  0.00000000          0     0.0
#> 5    5   0.00000000           0  0.00000000          0     0.0
#> 6    6   0.00000000           0  0.18181818          1     0.5
#> 7    7   0.09090909           1  0.27272727          1     1.0
#> 8    8   0.00000000           0  0.18181818          1     0.5
#> 9    9   0.09090909           1  0.09090909          1     1.0
#> 10  10   0.00000000           0  0.00000000          0     0.0
#> 11  11   0.00000000           0  0.00000000          0     0.0
#> 12  12   0.00000000           0  0.09090909          1     0.5
#> 13  13   0.00000000           0  0.00000000          0     0.0
#> 14  14   0.00000000           0  0.00000000          0     0.0
#> 15  15   0.18181818           1  0.36363636          1     1.0
#> 16  16   0.09090909           1  0.36363636          1     1.0
#> 17  17   0.09090909           1  0.36363636          1     1.0
#> 18  18   0.09090909           1  0.27272727          1     1.0
#> 19  19   0.27272727           1  0.45454545          1     1.0
#> 20  20   0.18181818           1  0.54545455          1     1.0
#> 21  21   0.00000000           0  0.09090909          1     0.5
#> 22  22   0.00000000           0  0.09090909          1     0.5
#> 23  23   0.00000000           0  0.00000000          0     0.0
#> 24  24   0.18181818           1  0.27272727          1     1.0
#> 25  25   0.00000000           0  0.18181818          1     0.5
#> 26  26   0.00000000           0  0.36363636          1     0.5
#> 27  27   0.09090909           1  0.27272727          1     1.0
#> 28  28   0.27272727           1  0.36363636          1     1.0
#> 29  29   0.27272727           1  0.36363636          1     1.0
#> 30  30   0.18181818           1  0.27272727          1     1.0
#> 31  31   0.36363636           1  0.36363636          1     1.0
#> 32  32   0.00000000           0  0.09090909          1     0.5

# After
devtools::load_all(.)
#> ℹ Loading performance
# Single score
z <- check_outliers(mtcars$mpg, method = c("iqr", "ci"), threshold = 0.7)
z.att <- attributes(z)
z.att$data
#>    Row Distance_IQR Outlier_IQR Distance_ci Outlier_ci Outlier
#> 1    1   0.36561743           0  0.05622837          0     0.0
#> 2    2   0.36561743           0  0.05622837          0     0.0
#> 3    3   0.71428571           0  0.36764706          0     0.0
#> 4    4   0.44309927           0  0.12543253          0     0.0
#> 5    5   0.07990315           0  0.34169550          0     0.0
#> 6    6   0.19612591           0  0.44550173          0     0.0
#> 7    7   0.93220339           0  1.10294118          1     0.5
#> 8    8   1.02421308           0  0.64446367          0     0.0
#> 9    9   0.71428571           0  0.36764706          0     0.0
#> 10  10   0.01694915           0  0.25519031          0     0.0
#> 11  11   0.25423729           0  0.49740484          0     0.0
#> 12  12   0.52542373           0  0.73961938          0     0.0
#> 13  13   0.35108959           0  0.58391003          0     0.0
#> 14  14   0.75786925           0  0.94723183          0     0.0
#> 15  15   1.68765133           0  1.77768166          1     0.5
#> 16  16   1.68765133           0  1.77768166          1     0.5
#> 17  17   0.85472155           0  1.03373702          1     0.5
#> 18  18   2.57384988           1  2.02854671          1     1.0
#> 19  19   2.18644068           1  1.68252595          1     1.0
#> 20  20   2.86440678           1  2.28806228          1     1.0
#> 21  21   0.46246973           0  0.14273356          0     0.0
#> 22  22   0.69975787           0  0.89532872          0     0.0
#> 23  23   0.75786925           0  0.94723183          0     0.0
#> 24  24   1.12590799           0  1.27595156          1     0.5
#> 25  25   0.01694915           0  0.25519031          0     0.0
#> 26  26   1.58595642           0  1.14619377          1     0.5
#> 27  27   1.33414044           0  0.92128028          0     0.0
#> 28  28   2.18644068           1  1.68252595          1     1.0
#> 29  29   0.64164649           0  0.84342561          0     0.0
#> 30  30   0.11380145           0  0.16868512          0     0.0
#> 31  31   0.79661017           0  0.98183391          0     0.0
#> 32  32   0.44309927           0  0.12543253          0     0.0

# Dataframe
z <- check_outliers(mtcars, method = c("iqr", "ci"), threshold = 0.7)
z.att <- attributes(z)
z.att$data
#>    Row Distance_IQR Outlier_IQR Distance_ci Outlier_ci Outlier
#> 1    1    1.0220601           0    1.000000          0     0.0
#> 2    2    0.7142857           0    1.000000          0     0.0
#> 3    3    1.4285714           0    1.000000          0     0.0
#> 4    4    1.4285714           0    1.000000          0     0.0
#> 5    5    0.9510174           0    1.000000          0     0.0
#> 6    6    1.6536204           0    1.607545          1     0.5
#> 7    7    1.8263473           1    1.358696          1     1.0
#> 8    8    1.4970646           0    1.293478          1     0.5
#> 9    9    3.5607543           1    2.941969          1     1.0
#> 10  10    0.7142857           0    1.000000          0     0.0
#> 11  11    0.7142857           0    1.000000          0     0.0
#> 12  12    1.3530637           0    1.274545          1     0.5
#> 13  13    0.8809235           0    1.000000          0     0.0
#> 14  14    0.9503558           0    1.000000          0     0.0
#> 15  15    2.9916681           1    2.693881          1     1.0
#> 16  16    3.2332928           1    2.903172          1     1.0
#> 17  17    3.1235897           1    2.808149          1     1.0
#> 18  18    2.5738499           1    2.028547          1     1.0
#> 19  19    2.4319728           1    2.645272          1     1.0
#> 20  20    2.8644068           1    2.288062          1     1.0
#> 21  21    1.5041808           0    1.230644          1     0.5
#> 22  22    1.2585034           0    1.607545          1     0.5
#> 23  23    0.7578692           0    1.000000          0     0.0
#> 24  24    1.8263473           1    1.493264          1     1.0
#> 25  25    1.2295253           0    1.311873          1     0.5
#> 26  26    1.6116994           0    1.293490          1     0.5
#> 27  27    2.1428571           1    1.962963          1     1.0
#> 28  28    2.1977087           1    1.962963          1     1.0
#> 29  29    2.4168297           1    2.032124          1     1.0
#> 30  30    2.1428571           1    2.333333          1     1.0
#> 31  31    3.5714286           1    3.666667          1     1.0
#> 32  32    1.0374150           0    1.038217          1     0.5
```

<sup>Created on 2022-09-07 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

### CODE REVIEW

**Comment by rempsyc** [comment]
@mattansb, do these new distance scores make any sense to you?

**Comment by mattansb** [comment]
I honestly have no idea... I never really filter outlier with automatic tools (because my data is always clean 😵‍💫)

Sorry 🤷‍♂️

**Comment by strengejacke** [comment]
> @mattansb, do these new distance scores make any sense to you?

@DominiqueMakowski any ideas?
@rempsyc Do you have any schedule when you can merge this PR? I'm planning to submit _parameters_ the next days or two weeks, and if I do, the update will probably break _performance_, so we would update it as well. The question is whether you would like this PR included in the next submission?

**Comment by rempsyc** [comment]
The PR is ready to merge, but I was hoping to get @bwiernik's blessing of the stats first 😬

**Comment by bwiernik** [comment]
I'll take a look this weekend

**Comment by rempsyc** [comment]
Little reminder ping @bwiernik just in case this is good timing

**Comment by DominiqueMakowski** [comment]
My two cents here is that it seems to make sense

**Review by strengejacke — APPROVED** [review]

**Pull request merged**
