### PR TITLE
Wrapper around ggdag and dagitty

### PR DESCRIPTION
**Pull request by strengejacke**
``` r
library(performance)

dag <- check_dag(
  y ~ x + b,
  outcome = "y",
  exposure = "x"
)
dag
#> # Correct adjustments for identifying direct effects
#> 
#> Model is correctly specified.
#> - Outcome: y
#> - Exposure: x
#> 
#> No adjustment needed to estimate the direct effect of x on y.
#> 
#> # Correct adjustments for identifying total effects
#> 
#> Model is correctly specified.
#> - Outcome: y
#> - Exposure: x
#> 
#> No adjustment needed to estimate the total effect of x on y.
plot(dag)
```

``` r

dag <- check_dag(
  y ~ x + b,
  outcome = "y",
  exposure = "x",
  adjusted = "b"
)
dag
#> # Correct adjustments for identifying direct effects
#> 
#> Model is correctly specified.
#> - Outcome: y
#> - Exposure: x
#> 
#> All minimal sufficient adjustments to estimate the direct effect were done.
#> 
#> # Correct adjustments for identifying total effects
#> 
#> Model is correctly specified.
#> - Outcome: y
#> - Exposure: x
#> 
#> All minimal sufficient adjustments to estimate the total effect were done.
plot(dag)
```

``` r

dag <- check_dag(
  y ~ x + b + c,
  x ~ b,
  outcome = "y",
  exposure = "x"
)
dag
#> # Correct adjustments for identifying direct effects
#> 
#> Incorrectly adjusted!
#> - Outcome: y
#> - Exposure: x
#> 
#> To estimate the direct effect, *also* adjust for: b.
#> Currently, the model does not adjust for any variables.
#> 
#> # Correct adjustments for identifying total effects
#> 
#> Incorrectly adjusted!
#> - Outcome: y
#> - Exposure: x
#> 
#> To estimate the total effect, *also* adjust for: b.
#> Currently, the model does not adjust for any variables.
plot(dag)
```

``` r

dag <- check_dag(
  y ~ x + b + c,
  x ~ b,
  outcome = "y",
  exposure = "x",
  adjusted = "c"
)
dag
#> # Correct adjustments for identifying direct effects
#> 
#> Incorrectly adjusted!
#> - Outcome: y
#> - Exposure: x
#> 
#> To estimate the direct effect, *also* adjust for: b and c.
#> Currently, the model currently only adjusts for c.
#> 
#> # Correct adjustments for identifying total effects
#> 
#> Incorrectly adjusted!
#> - Outcome: y
#> - Exposure: x
#> 
#> To estimate the total effect, *also* adjust for: b and c.
#> Currently, the model currently only adjusts for c.
plot(dag)
```

<sup>Created on 2024-08-03 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

### CODE REVIEW

**Comment by strengejacke** [comment]
@easystats/core-team What do you think? A "check" function for DAGs in _performance_? Plots still needs some improvements (e.g. get rid of the "adjusted line" legend).

Benefits over ggdag:
- you can include "adjusted" variables in the dag-definition, using the `adjusted` argument
- `plot()` is intended to compare current to required model, not to create final plots (though we could add this, but ggdag is sufficient here, or not?)

**Comment by mattansb** [comment]
Can you give an example of where this would fit in the model-building workflow?

**Comment by strengejacke** [comment]
``` r
library(performance)
# error for cyclic model
dag <- check_dag(
  y ~ x + b + c + d,
  x ~ c + d,
  b ~ x,
  b ~ y,
  outcome = "y",
  exposure = "x",
  adjusted = "c"
)
#> Error: Model is cyclic. Causal effects can't be determined for cyclic models.
#>   Please remove cycles from the model. To do so, check following
#>   variables: b and y

# collider-bias
dag <- check_dag(
  y ~ x + c + d,
  x ~ c + d,
  b ~ x,
  b ~ y,
  outcome = "y",
  exposure = "x",
  adjusted = "c"
)
dag
#> # Correct adjustments for identifying direct effects
#> 
#> Incorrectly adjusted!
#> - Outcome: y
#> - Exposure: x
#> 
#> To estimate the direct effect, also adjust for: c and d.
#> Currently, the model currently only adjusts for c.
#> 
#> # Correct adjustments for identifying total effects
#> 
#> Incorrectly adjusted!
#> - Outcome: y
#> - Exposure: x
#> 
#> To estimate the total effect, also adjust for: c and d.
#> Currently, the model currently only adjusts for c.
plot(dag)
```



<sup>Created on 2024-08-03 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

**Comment by strengejacke** [comment]
> Can you give an example of where this would fit in the model-building workflow?

What do you exactly mean? You can use this at the point where you involve DAGs. Like you would do with the online tool dagitty.net, you can easily specify your "dependencies" (causal paths) via familiar formula-syntax and then check if you adjusted correctly or not.

The "check" here is that you get the corrected DAG, telling you what you need to adjust for.

**Comment by strengejacke** [comment]
not sure why the geoms look so ugly in the reprex, though

**Pull request merged**
