### PR TITLE
remove principal_components to avoid conflict

### PR DESCRIPTION
**Pull request by DominiqueMakowski**

### CODE REVIEW

**Comment by strengejacke** [comment]
Do you want to remove it directly before deprecating it?

**Comment by DominiqueMakowski** [comment]
I think it should be okay to just remove it, but as you want

**Comment by strengejacke** [comment]
Just saw in sjPlot I use `performance:: principal_components()`. So I have to update sjPlot before performance.

**Comment by DominiqueMakowski** [comment]
oops 🙊

**Pull request merged**
