### PR TITLE
First draft of R2

### PR DESCRIPTION
**Pull request by strengejacke**
Support for first simple models, and maybe a good draft to think about design choices (here especially the `type`-argument).

### CODE REVIEW

**Comment by strengejacke** [comment]
Maybe we can add aliases for them, but I would prefer to keep short-named alternatives of the functions as well... Having "direct measure" like `r2_nagelkerke()` or `performance_r2_nagelkerke()` sounds good!

**Comment by DominiqueMakowski** [comment]
Keeping both a short name and a long name is indeed a solution for both accessibility (finding package functionalities for newcomers) and efficiency (for programmers)!

**Comment by strengejacke** [comment]
Shall we add more functionality for this PR, or merge this one and then add step-by-step further models?

**Comment by DominiqueMakowski** [comment]
let's merge it!

**Pull request merged**
