### PR TITLE
Prepare CRAN release

### PR DESCRIPTION
**Pull request by strengejacke**

### CODE REVIEW

**Comment by IndrajeetPatil** [comment]
Some workflows are failing because of _cplm_ issues: https://cran.r-project.org/web/checks/check_results_cplm.html

The warning in R CMD Check (`'.T2Cmat' is deprecated`) is coming from _Matrix_, either via _TMB_ or _glmmTMB_ and can be ignored.

**Comment by strengejacke** [comment]
> The warning in R CMD Check ('.T2Cmat' is deprecated) is coming from Matrix, either via TMB or glmmTMB and can be ignored.

Yeah, I was in contact with the Matrix maintainer (he contacted affected packages), and it turned out it's a TMB issue, so nothing we can/need to do from our side.

**Review by strengejacke — COMMENTED** [review]
image

image

😬

**Comment by IndrajeetPatil** [comment]
You can blame indentation lints for now because they are false positives. We are working on aligning _styler_ and _lintr_ on this.

**Comment by strengejacke** [comment]
revdep checks all OK.

**Comment by strengejacke** [comment]
submitted

**Pull request merged**
