### PR TITLE
Export S3 methods for model_performance generic #452

### PR DESCRIPTION
**Pull request by jimrothstein**

### CODE REVIEW

**Comment by IndrajeetPatil** [comment]
@jimrothstein Thanks a lot for doing this! I have modified it a bit to also update `NAMESPACE`.

@strengejacke I had to move the default method to where generic is defined because otherwise it won't be found by other methods that rely on the default method. The other solution would have been to use `Collate` field in `DESCRIPTION`, but I am not a fan of that option.

**Comment by jimrothstein** [comment]
@strengejacke yes, I should have checked where the .default method was defined.

**Comment by IndrajeetPatil** [comment]
@jimrothstein Do you mind also updating the NEWS.md file and mention these changes? 

Remember to include the PR number and your GitHub handle in the news item.

**Comment by jimrothstein** [comment]
@IndrajeetPatil,  Yes, will do, but tomorrow ...    (was trying to find away to generate all the  `@export` for the methods via code using knitr ... did not work.)

**Comment by strengejacke** [comment]
> @strengejacke I had to move the default method to where generic is defined because otherwise it won't be found by other methods that rely on the default method. The other solution would have been to use `Collate` field in `DESCRIPTION`, but I am not a fan of that option.

Sounds good to me!

**Comment by IndrajeetPatil** [comment]
@jimrothstein Why did you close this? 

@strengejacke I think this can be reopened and merged?

**Comment by jimrothstein** [comment]
@IndrajeetPatil @strengejacke 

Hadn't heard from anyone in long time;  and was cleaning repos.   

Did not realize affect here, which is my fault, but I did not know.

**Comment by jimrothstein** [comment]
@IndrajeetPatil @strengejacke 


Do you want me to continue with tinytest::  checks ?

**Comment by strengejacke** [comment]
Closing this for now, for two reasons:
1) https://github.com/easystats/parameters/pull/807#issuecomment-1494687759
2) Not sure how to resolve conflicts with the command line.

**Pull request closed without merging**
