### PR TITLE
Add tests for check_outliers

### PR DESCRIPTION
**Pull request by rempsyc**
First attempt at writing tests for easystats so welcome any feedback. I removed the `if (requiet("testthat") && requiet("performance"))` at the beginning since we discussed it wasn't necessary earlier since performance will already be installed and testthat as well.

### CODE REVIEW

**Comment by IndrajeetPatil** [comment]
Thansk, @rempsyc! 

Can you please have a look at the build failures? They are not to be expected.

**Review by strengejacke — APPROVED** [review]

**Comment by strengejacke** [comment]
Looks like one issue has to be fixed.

**Comment by IndrajeetPatil** [comment]
The error is the following:

```r
 ----------- FAILURE REPORT -------------- 
 --- failure: the condition has length > 1 ---
 --- srcref --- 
 at D:/a/performance/performance/check/performance.Rcheck/00_pkg_src/performance/R/check_outliers.R#1216: 
```

**Comment by IndrajeetPatil** [comment]
```r
  ══ Failed tests ════════════════════════════════════════════════════════════════
  ── Failure ('test-check_outliers.R:295'): nlme multiple methods ────────────────
  `check_outliers(model, method = c("zscore_robust", "iqr"))` did not throw the expected error.
  
  [ FAIL 1 | WARN 10 | SKIP 3 | PASS 309 ]
```

**Comment by strengejacke** [comment]
I think we can remove that test, because this error should actually never occur.

**Comment by rempsyc** [comment]
Thanks! The failing test is successful when run locally though that's weird.

Note that while doing the tests, I realized that some tests that should be working were not working, so I have commented them out for now. I did not want to withhold all the other successful tests waiting for me to debug a few specific cases. However, I will come back to them later and attempt to fix them as well.

**Pull request merged**
