### PR TITLE
Use get_modelmatrix instead model.matrix

### PR DESCRIPTION
**Pull request by strengejacke**

### CODE REVIEW

**Comment by bwiernik** [comment]
Think you're missing some commits?

**Comment by strengejacke** [comment]
Yes, not sure why? I wanted to revert the changes with `get_modelmatrix()` from master and save them in this branch for later merge, so I can release a "working" branch for the JOSS paper...

**Comment by bwiernik** [comment]
You should do this:

1. Check out the last commit that you want to be on master and make a new branch from it called `get_modelmatrix`.
2. Cherry pick the commits from master into `get_modelmatrix`
3. reset --hard mast to the last commit you want, then push --force it

**Comment by strengejacke** [comment]
I probably delete this branch and simply change model.matrix to get_modelmatrix later... isn't a really big deal.

**Pull request closed without merging**
