### PR TITLE
Add tests, fix bug with model-based outliers and multiple thresholds

### PR DESCRIPTION
**Pull request by rempsyc**
In this PR, I've fixed some (commented out) tests that were failing. One of the reasons they were failing was that I needed to also apply the fix from #497 to model-based outliers (to support user-specified thresholds). Once that was done, the tests were working.

### CODE REVIEW

**Comment by IndrajeetPatil** [comment]
```r
══ Failed tests ════════════════════════════════════════════════════════════════
── Failure ('test-check_outliers.R:261'): pareto which ─────────────────────────
which(check_outliers(model, method = "pareto", threshold = list(pareto = 0.5))) (`actual`) not equal to 17 (`expected`).

  `actual`: 9 17
`expected`:   17

[ FAIL 1 | WARN 11 | SKIP 3 | PASS 311 ]
```

**Comment by rempsyc** [comment]
Ok, I've corrected that test output. Let's see what happens now.

**Comment by rempsyc** [comment]
Seems like it's working... but weird thing is, locally for that test (directly in console, with `devtools::test()`, or with `devtools::check(args = c('--as-cran','--run-donttest'))`), I need to expect `17` only, not `c(9, 17)`, else it fails. On GHA it's the opposite. Is it common to have consistent inconsistency between local and GHA like that?

I don't think the pareto method is supposed to have an element of randomness to it that could explain this discrepancy...

**Comment by strengejacke** [comment]
Thanks!

**Comment by strengejacke** [comment]
> Seems like it's working... but weird thing is, locally for that test (directly in console, with devtools::test(), or with devtools::check(args = c('--as-cran','--run-donttest'))), I need to expect 17 only, not c(9, 17), else it fails. On GHA it's the opposite. Is it common to have consistent inconsistency between local and GHA like that?

Often, it's an issue of different setups. It's not always clear why results differ, and in particular with Stan, I feel like often failures are not due to errors in my packages, but to the difficult installation setup in the background.

**Comment by strengejacke** [comment]
Locally, it's also only case 17 for me. I added a seed, maybe that might change the test results?

**Comment by strengejacke** [comment]
setting seeds resolves this issue. We should pay attention to always using seed for models with sampling.

**Pull request merged**
